export const API_URL = "$SIBBAY_BACKEND_API_URL"
export const PREVIEW_TOOL_URL = "http://mritools.sibbay.ai/v2"
export const ALIYUN_OAUTH_CLIENT_ID = "$SIBBAY_ALIYUN_RAM_OAUTH_APPID"
export const ALIYUN_OAUTH_REDIRECT_URI = "$SIBBAY_ALIYUN_OAUTH_REDIRECT_URI"
export const ALIYUN_OAUTH_RESPONSE_TYPE = "code"
export const ALIYUN_OAUTH_URL = "https://signin.aliyun.com/oauth2/v1/auth?client_id=" + ALIYUN_OAUTH_CLIENT_ID + "&redirect_uri=" + ALIYUN_OAUTH_REDIRECT_URI + "&response_type=" + ALIYUN_OAUTH_RESPONSE_TYPE + "&state="
export const RUN_ENV = "test"